[package]
name = "ubercorn"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rgb = "0.8.25"
spidev = "0.4.0"
rand = "0.7.3"
